# File: azure-pipelines.yaml

name: $(Date:yyyyMMdd)$(Rev:.r)

#trigger:
#  branches:
#    include:
#      - alpha
#      - monolithic
#  paths:
#    exclude:
#      - docs/*

#pr:
#  - alpha
#  - main

resources:
  - repo: self

variables:
  - template: variables.yaml

stages:
#  - stage: Tag
#    displayName: Get Tag
#    pool:
#        vmImage: 'vs2017-win2016'
#    jobs:
#      - job: release
#        displayName: semantic release
#        variables:
#          GITHUB-TOKEN: $(_GITHUB_TOKEN)
#          NPM-TOKEN: $(_NPM_TOKEN)
#        steps:
 #         - script:  >
 #             npx 
 #             -p semantic-release
 #             -p @semantic-release/changelog
 #             -p @semantic-release/git
 #             -p semantic-release-ado
 #             semantic-release
#            displayName: 'Tag release'
#            env: { GH_TOKEN: $(GITHUB-TOKEN), NPM_TOKEN: $(NPM-TOKEN) }
#          
#          - powershell: |
#              echo "##vso[task.setvariable variable=versionNumber;isOutput=true]$(nextRelease)"
#            name: setOutputVar
  - stage: CI
    displayName: Continuous Integration
#    dependsOn: Tag
#    variables:
#      _NEXT_RELEASE_TAG: $[ stageDependencies.Tag.release.outputs['setOutputVar.versionNumber'] ]
    pool:
      vmImage: Ubuntu-16.04
    jobs:
      - template: ./build.yml
        parameters:
          package: $(package)
#          tag: $(_NEXT_RELEASE_TAG)

#  - stage: CD
#    displayName: Continuous Deployment
#    variables:
#      _NEXT_RELEASE_TAG: $[ stageDependencies.Tag.release.outputs['setOutputVar.versionNumber'] ]
#    condition: 
#    jobs:
#      - template: ./deploy.yml
#        parameters:
#          buildLocation: $(Pipeline.Workspace)/**/*-$(_NEXT_RELEASE_TAG).zip
#          resourceGroupName: $(serviceConnection)
#          azureSubscription: $(serviceConnection)
#          environment: '$(serviceConnection)-$(pushBranch)'
#          appName: '$(appName)'
#          notifyUsers: '$(notifyUsers)'
        