#parameters:
#  - name: 'package'
#    default: false
#  - name: 'tag'

jobs:
  - job: Build
    steps:
      # Build artifacts
      - script: yarn
        displayName: Install Packages
#      - script: yarn lint
#        displayName: linting
#      - script: yarn test
#        displayName: unit testing
#      - script: yarn build
#        displayName: build
      # - script: yarn start:container && yarn test-integration
      #   displayName: IntegrationTest

  - job: Package
 #   condition: and(succeeded(), eq(variables['package'], true))
    steps:
      # Run to package
      - script: yarn install --production
        displayName: prune dependencies
      - script: cp -R node_modules ./dist
        displayName: copy node modules
      - script: yarn zip
      # publish package as artifact
      - task: PublishPipelineArtifact@1
        displayName: publish package
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifact: 'build.zip'